#include <algorithm>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <cstdio>
#include <cstdlib>
#include <cctype>
#include <climits>
#include <cmath>

using namespace std;

// split, auto generated by FileEdit
vector<string> split( const string& s, const string& delim =" " ) {
    vector<string> res;
    string t;
    for ( int i = 0 ; i != s.size() ; i++ ) {
	if ( delim.find( s[i] ) != string::npos ) {
	    if ( !t.empty() ) {
		res.push_back( t );
		t = "";
	    }
	} else {
	    t += s[i];
	}
    }
    if ( !t.empty() ) {
	res.push_back(t);
    }
    return res;
}

vector<int> splitInt( const string& s, const string& delim =" " ) {
    vector<string> tok = split( s, delim );
    vector<int> res;
    for ( int i = 0 ; i != tok.size(); i++ )
	res.push_back( atoi( tok[i].c_str() ) );
    return res;
}
// split, auto generated by FileEdit

// BEGIN CUT HERE
#define ARRSIZE(x) (sizeof(x)/sizeof(x[0]))

template<typename T> void print( T a ) {
    cerr << a;
}
static void print( long long a ) {
    cerr << a << "L";
}
static void print( string a ) {
    cerr << '"' << a << '"';
}
template<typename T> void print( vector<T> a ) {
    cerr << "{";
    for ( int i = 0 ; i != a.size() ; i++ ) {
	if ( i != 0 ) cerr << ", ";
	print( a[i] );
    }
    cerr << "}" << endl;
}
template<typename T> void eq( int n, T have, T need ) {
    if ( have == need ) {
	cerr << "Case " << n << " passed." << endl;
    } else {
	cerr << "Case " << n << " failed: expected ";
	print( need );
	cerr << " received ";
	print( have );
	cerr << "." << endl;
    }
}
template<typename T> void eq( int n, vector<T> have, vector<T> need ) {
    if( have.size() != need.size() ) {
	cerr << "Case " << n << " failed: returned " << have.size() << " elements; expected " << need.size() << " elements.";
	print( have );
	print( need );
	return;
    }
    for( int i= 0; i < have.size(); i++ ) {
	if( have[i] != need[i] ) {
	    cerr << "Case " << n << " failed. Expected and returned array differ in position " << i << ".";
	    print( have );
	    print( need );
	    return;
	}
    }
    cerr << "Case " << n << " passed." << endl;
}
static void eq( int n, string have, string need ) {
    if ( have == need ) {
	cerr << "Case " << n << " passed." << endl;
    } else {
	cerr << "Case " << n << " failed: expected ";
	print( need );
	cerr << " received ";
	print( have );
	cerr << "." << endl;
    }
}
// END CUT HERE

/************** Program  Begin *********************/

class JustifyText {
public:
    vector <string> format(vector <string> text) {
	vector <string> res = text;
	int maxlen = 0;

	for (int i = 0; i < text.size(); i++) {
		if (text[i].size() > maxlen) {
			maxlen = text[i].size();
		}
	}

	for (int i = 0; i < text.size(); i++) {
		if (text[i].size() < maxlen) {
			for (int j = 0; j < maxlen - text[i].size(); j++) {
				res[i] = " " + res[i];
			}
		}
	}
	return res;
    }

};

/************** Program End ************************/

// BEGIN CUT HERE
void main( int argc, char* argv[] ) {
    {
	string textARRAY[] = {"BOB","TOMMY","JIM"};
	vector <string> text( textARRAY, textARRAY+ARRSIZE(textARRAY) );
	string retrunValueARRAY[] = {"  BOB", "TOMMY", "  JIM" };
	vector <string> retrunValue( retrunValueARRAY, retrunValueARRAY+ARRSIZE(retrunValueARRAY) );
	JustifyText theObject;
	eq(0, theObject.format(text),retrunValue);
    }
    {
	string textARRAY[] = {"JOHN","JAKE","ALAN","BLUE"};
	vector <string> text( textARRAY, textARRAY+ARRSIZE(textARRAY) );
	string retrunValueARRAY[] = {"JOHN", "JAKE", "ALAN", "BLUE" };
	vector <string> retrunValue( retrunValueARRAY, retrunValueARRAY+ARRSIZE(retrunValueARRAY) );
	JustifyText theObject;
	eq(1, theObject.format(text),retrunValue);
    }
    {
	string textARRAY[] = {"LONGEST","A","LONGER","SHORT"};
	vector <string> text( textARRAY, textARRAY+ARRSIZE(textARRAY) );
	string retrunValueARRAY[] = {"LONGEST", "      A", " LONGER", "  SHORT" };
	vector <string> retrunValue( retrunValueARRAY, retrunValueARRAY+ARRSIZE(retrunValueARRAY) );
	JustifyText theObject;
	eq(2, theObject.format(text),retrunValue);
    }
}
// END CUT HERE
