import math,string,itertools,fractions,heapq,collections,re,array,bisect,random

class PermutationCounts:
    def countPermutations(self, N, pos):
        
        return

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pf 2.3.0
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, hasAnswer, p2):
	obj = PermutationCounts()
	startTime = time.clock()
	answer = obj.countPermutations(p0, p1)
	endTime = time.clock()
	res = True
	if (hasAnswer):
		res = answer == p2
	
	sys.stdout.write(str("Test ") + str(testNum) + str(" "))
	if (not res):
		print(str("failed."))
		sys.stdout.write(str("expected: "))
		print(str("\t") + str(p2))
		sys.stdout.write(str("received: "))
		print(str("\t") + str(answer))
		print(str(""))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		sys.stdout.write(str("passed.      "))
		sys.stdout.write(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
		print(str(""))
	else:
		print(str("OK, but is it right?"))
	
	return res

all_right = True
tests_disabled = False


# ----- test 0 -----
disabled = False
p0 = 5
p1 = (3,)
p2 = 9
all_right = (disabled or KawigiEdit_RunTest(0, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 1 -----
disabled = False
p0 = 13
p1 = (12,11,10,9,8,7,6,5,4,3,2,1)
p2 = 1
all_right = (disabled or KawigiEdit_RunTest(1, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 2 -----
disabled = False
p0 = 13
p1 = ()
p2 = 1
all_right = (disabled or KawigiEdit_RunTest(2, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 3 -----
disabled = False
p0 = 9
p1 = (2,4,5)
p2 = 1421
all_right = (disabled or KawigiEdit_RunTest(3, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 4 -----
disabled = False
p0 = 80
p1 = (31,41,59,26,53,58,9,79,32,3,8,46)
p2 = 82650786
all_right = (disabled or KawigiEdit_RunTest(4, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 5 -----
disabled = False
p0 = 875
p1 = (295,311,98,345,420,547,646,734,380,325,608,783,141,65,305,437,769,252,44,872,123,6,50,507,450,426,343,740,69,695,101,607,597,535,342,307,329,837,803,237,459,444,498,15,712,134,473,14,715,223,787,192,710,750,193,293,242,652,212,580,545,488,506,533,774,460,285,534,350,210,559,805,686,67,159,541,706,514,657,801,373,754,310,800,589,736,863,675,254,283,604,27,628,103,81,235,677,461,609,30,581,75,756,688,262,563,679,21,217,515,836,868,13,728,717,309,267,767,259,414,332,744,129,859,4,179,632,415,278,812,79,77,784,573,433,865,407,121,477,567,790,127,593,57,674,114,239,599,552,738)
p2 = 169176190
all_right = (disabled or KawigiEdit_RunTest(5, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

if (all_right):
	print(str(""))
	if (tests_disabled):
		print(str("You're a stud (but some test cases were disabled)!"))
	else:
		print(str("You're a stud (at least on given cases)!"))
	
else:
	print(str("Some of the test cases had errors."))

# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pf 2.3.0!
